@branch={{hostname}}/api/v1/account
@contentType=application/json
@authToken=JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0eXAiOiJhY2Nlc3MiLCJleHAiOjE2NTAyNDU5ODgsImlhdCI6MTY1MDI0MjM4OCwianRpIjoiYzFmMjcxMGZlZTFkNDFkNmI0NjdiMDM4ZDdmZGQ2MGMiLCJ1dWlkIjoiYjAzNDMzODQtMDE1Mi00NjcxLWE3ZDYtYzIxMjJhNjVlYWIxIiwiaXNzIjoiREFBUyJ9.87WJbdnHNG3YycIahpQ0Cnp4AXc9086qOZpwAeqXBUM

###
GET {{branch}}/all

###
POST {{branch}}/signup
Content-Type: {{contentType}}

{
    "email": "hig@emovaw.za",
    "first_name": "Hilda",
    "last_name": "Ramirez",
    "phone": "41276641",
    "password": "hig@emovaw.za"
}

### Exception handler
POST {{branch}}/signup
Content-Type: {{contentType}}

{"first_name": "561251", "last_name": "512515", "email": "nguyenchinhkhoi@gmail.com", "phone": "41276641", "password": "ytF4d6R65YqRUdb"}

###
POST {{branch}}/signin
Content-Type: {{contentType}}

{
    "email": "hig@emovaw.za",
    "password": "hig@emovaw.za"
}

###
GET {{branch}}/about
Content-Type: {{contentType}}
Authorization: {{authToken}}

###
DELETE {{branch}}/signout
