@branch={{hostname}}/api/v1/account
@contentType=application/json
@authToken=JWT {{signin.response.body.access_token}}

###
POST {{branch}}/signup
Content-Type: {{contentType}}

{
    "email": "hig@emovaw.za",
    "first_name": "Hilda",
    "last_name": "Ramirez",
    "phone": "41276641",
    "password": "hig@emovaw.za"
}

###
# @name signin
POST {{branch}}/signin
Content-Type: {{contentType}}

{
    "email": "hig@emovaw.za",
    "password": "hig@emovaw.za"
}

###
GET {{branch}}/about
Content-Type: {{contentType}}
Authorization: {{authToken}}

###
DELETE {{branch}}/signout
