# Generated by Django 4.0.3 on 2022-04-20 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='user_item',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('item', 'order_uuid'), name='order_item'),
        ),
    ]
