# Generated by Django 4.0.3 on 2022-04-09 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producthistory',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainframe.product'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['machine_id'], name='mainframe_o_machine_d9d00d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_id'], name='mainframe_o_order_i_a613eb_idx'),
        ),
        migrations.AddIndex(
            model_name='producthistory',
            index=models.Index(fields=['item'], name='mainframe_p_item_id_97ee28_idx'),
        ),
    ]
