# Generated by Django 4.0.4 on 2022-04-25 06:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='machine',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_set', to='mainframe.order'),
        ),
        migrations.CreateModel(
            name='OrderQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainframe.machine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainframe.order')),
            ],
            options={
                'verbose_name': 'order queue',
                'verbose_name_plural': 'order queues',
            },
        ),
    ]
