# Generated by Django 4.0.3 on 2022-04-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainframe', '0002_order_order_id_producthistory_item_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='mainframe_o_machine_d9d00d_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='machine_id',
            new_name='machine',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['machine'], name='mainframe_o_machine_90b959_idx'),
        ),
    ]
