@branch={{hostname}}/api/v1/order
@contentType=application/json
@authToken=JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0eXAiOiJhY2Nlc3MiLCJleHAiOjE2NTAyNDU5ODgsImlhdCI6MTY1MDI0MjM4OCwianRpIjoiYzFmMjcxMGZlZTFkNDFkNmI0NjdiMDM4ZDdmZGQ2MGMiLCJ1dWlkIjoiYjAzNDMzODQtMDE1Mi00NjcxLWE3ZDYtYzIxMjJhNjVlYWIxIiwiaXNzIjoiREFBUyJ9.87WJbdnHNG3YycIahpQ0Cnp4AXc9086qOZpwAeqXBUM

###
GET {{branch}}/view_order?order_id=2
Content-Type: {{contentType}}
Authorization: {{authToken}}

###
PUT {{branch}}/item_quantity
Content-Type: {{contentType}}
Authorization: {{authToken}}

{
    "order_id": 2,
    "item_uuid": "e5fb8ff4-9520-5118-8195-290803e57460",
    "new_quantity": 269
}