@branch={{hostname}}/api/v1/order
@contentType=application/json
@authHeader=JWT {{signin.response.body.access_token}}

###
# @name signin
POST {{hostname}}/api/v1/account/signin
Content-Type: {{contentType}}

{
    "email": "hig@emovaw.za",
    "password": "hig@emovaw.za"
}

###
GET {{branch}}/my_orders
Content-Type: {{contentType}}
Authorization: {{authHeader}}

###
GET {{branch}}/my_orders?history=paid
Content-Type: {{contentType}}
Authorization: {{authHeader}}

###
GET {{branch}}/my_orders?history=all
Content-Type: {{contentType}}
Authorization: {{authHeader}}

###
GET {{branch}}/view_order?order_uuid=4ad6ece6-8e17-59ac-b140-a7afb9b77fbd
Content-Type: {{contentType}}
Authorization: {{authHeader}}

### New order
PUT {{branch}}/edit_order
Content-Type: {{contentType}}
Authorization: {{authHeader}}

{
    "order_uuid": null,
    "item_uuid": "ba50b773-0580-5da1-b4fa-56f01696a1cb",
    "quantity": 3
}

### New item in order
PUT {{branch}}/edit_order
Content-Type: {{contentType}}
Authorization: {{authHeader}}

{
    "order_uuid": "4ad6ece6-8e17-59ac-b140-a7afb9b77fbd",
    "item_uuid": "baf9c355-a040-5f07-a669-a92e6245bf3e",
    "quantity": 4
}

### Edit item in order
PUT {{branch}}/edit_order
Content-Type: {{contentType}}
Authorization: {{authHeader}}

{
    "order_uuid": "4ad6ece6-8e17-59ac-b140-a7afb9b77fbd",
    "item_uuid": "e5fb8ff4-9520-5118-8195-290803e57460",
    "quantity": 269
}

### Delete item in order
PUT {{branch}}/edit_order
Content-Type: {{contentType}}
Authorization: {{authHeader}}

{
    "order_uuid": "4ad6ece6-8e17-59ac-b140-a7afb9b77fbd",
    "item_uuid": "072c8269-eda2-5085-8d5f-4811e5adb80d",
    "quantity": 0
}

###
DELETE {{branch}}/delete_order
Content-Type: {{contentType}}
Authorization: {{authHeader}}

{
    "order_uuid": "4ad6ece6-8e17-59ac-b140-a7afb9b77fbd"
}

###
PUT {{branch}}/checkout
Content-Type: {{contentType}}
Authorization: {{authHeader}}

{
    "order_uuid": "4ad6ece6-8e17-59ac-b140-a7afb9b77fbd",
    "machine_uuid": "d89647bf-ebdb-53c5-ae26-99d5256439c5"
}
