@branch={{hostname}}/api/v1/machine
@contentType=application/json
@machineUUID=UUID d89647bf-ebdb-53c5-ae26-99d5256439c5

###
GET {{branch}}/all

###
GET {{branch}}/about
Content-Type: {{contentType}}
X-MACHINE-UUID: {{machineUUID}}

###
GET {{branch}}/order_queue
Content-Type: {{contentType}}
X-MACHINE-UUID: {{machineUUID}}

###
POST {{branch}}/complete_order
Content-Type: {{contentType}}

{
  "order_uuid": "baaa78dd-dbd4-4a2a-b0bd-7a071178d76c"
}
