@branch={{hostname}}/api/v1/machine
@machineUUID=UUID d89647bf-ebdb-53c5-ae26-99d5256439c5

###
GET {{branch}}/all

###
GET {{branch}}/about
Content-Type: application/json
X-MACHINE-UUID: {{machineUUID}}

###
GET {{branch}}/order_queue
Content-Type: application/json
X-MACHINE-UUID: {{machineUUID}}
